### PR TITLE
Catalog of things - Ruby Capstone

### PR DESCRIPTION
**Pull request by ReshyResh**
# Ruby Group Capstone
#### Logic

    - Each class from the [UML class diagram](https://i.imgur.com/EwxB4U5.png) should be created in a separate .rb file.
    - All associations (1-to-many relationships) and aggregations (parent-child relationships) between classes should be
        implemented.
    - All properties visible in the diagram should be defined and set up in the constructor method. _Exception: properties for 
    the 1-to-many relationships should NOT be set in the constructor method. Instead, they should have a custom setter method created.
    - All methods visible in the diagram should be implemented:
    - add_item method (in all classes that have that method)
        - should take an instance of the Item class as an input.
        - should add the input item to the collection of items.
        - should add self as a property of the item object (by using the correct setter from the item object).
    - can_be_archived?() in the Item class
        - should return true if published_date is older than 10 years.
        - otherwise, it should return false.
    - move_to_archive() in the Item class
        - should reuse can_be_archived?() method.
        - should change the archived property to true if the result of the can_be_archived?() method is true.
        - should do nothing if the result of the can_be_archived?() method is false.
    - Add unit tests for all implemented methods.

#### User interface

    - Create a main.rb file that will serve as your console app entry-point.
    - Your console app, at the start, should:
        - Present the user with a list of options to perform.
        - Let users choose an option.
        - If needed, ask for parameters for the option.
        - Have a way to quit the app.
    - The following options should be available:
        - List all books
        - List all music albums
        - List all movies
        - List of games
        - List all genres (e.g 'Comedy', 'Thriller')
        - List all labels (e.g. 'Gift', 'New')
        - List all authors (e.g. 'Stephen King')
        - List all sources (e.g. 'From a friend', 'Online shop')
        - Add a book
        - Add a music album
        - Add a movie
        - Add a game
     - All data should be preserved by saving collections in .json files.

### Database
    - Create a schema.sql file with tables that will be analogical to the structure of the classes in your app. As you cannot 
    implement inheritancein the database tables - add all properties and associations from the parent Item 
    class as table columns to all tables based on the child classes. Thanks to that it can be used to store data in the future.

### Video presentation
Click [here](https://drive.google.com/file/d/1apQFmWLhWAESvQlIl8FP9dAtk1Sz_HBW/view)

### CODE REVIEW

**Review by od-c0d3r — CHANGES_REQUESTED** [review]
Asslam Alikom team, @ReshyResh @DammyShittu @faizi2500..  

Hi 👋🏽, 
While you made a great effort in this project, unfortunately, I cannot proceed to review your code

## Invalid Code Review Request

You have submitted a project, that doesn't fulfill one of the project `General Requirements` :

You have submitted a project, that doesn't fulfill one of the project **General requirements**  : 
- [x] Make sure that you used the correct Gitflow. [LINK](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/git-github/articles/gitflow.md) 
  -  Ex: make your pull requests from the `feature` branch to the `develop` branch.
  - Link on how easily you can change the pull request base branch [LINK](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/changing-the-base-branch-of-a-pull-request) 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Happy coding!👏:heart:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **Does not count** into the code reviews limit._

**Comment by DammyShittu** [comment]
Hi @od-c0d3r,

According to the [Code Review](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/code-review/articles/code_review_flow_group_projects.md) section in the [link](https://github.com/microverseinc/curriculum-ruby/blob/main/group-capstone/catalog_of_my_things.md#:~:text=make%20sure%20that%20you%20used%20correct%20gitflow.) you shared, a pull request for an external code review should be opened from the `dev` branch to the `main` branch.

I think there's a mix-up somewhere. Attached is a screenshot of the external code review guideline. 👇

eSoQfYo
 
Kindly check and acknowledge 😁 

Cheers.

**Comment by od-c0d3r** [comment]
@DammyShittu, You are right. nothing required from your end. :+1: 
Kindly submit for another code review and and shortly your project will be reviewed.

Your project is awesome any way :100: :smile:
Good luck :1st_place_medal:

**Review by Emmyn5600 — APPROVED** [review]
Hi @DammyShittu, @faizi2500  and @ReshyResh

Highlights:

- Your database is well structured
- You have done almost all the requirements
- All tests are passing successfully
- Data is being stored after exiting the app.
- Nice UI, your project looks and works perfectly.

Your project is complete! There is nothing else to say other than... it's time to merge it :shipit:
Congratulations! :tada:


 #### Optional suggestions,.
 
 - N/A
 
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding! :clap: :clap: :clap:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

#### _**Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.**_
------------------------------------------------------------------------------------------------------------------------------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)

**Comment by DammyShittu** [comment]
Thank you for the review, @Emmyn5600 👏

**Pull request merged**
